.nh
.TH RCB 1 "0.12.0" RCB "User Manuals"
.SH \fBNAME\fR
rcb-delete
.SH \fBSYNOPSIS\fR
\fBrcb delete\fP [\fIoptions\fP] [\fIarguments\fP]
.br
\fBrcb delete\fP [\fIarguments\fP] [\fIoptions\fP]
.br
\fBrcb delete\fP [\fIoptions\fP]
.br
\fBrcb delete\fP [\fIarguments\fP]
.br
.SH \fBDESCRIPTION\fR
The delete command allows for file deletion. Upon use it will save essential details into .rcb/data/rcb.sqlite3 about the file before moving it into the .rcb/file/ directory. If an existing file entry is found with the same filename it will automatically increment it with a number to prevent filename collisions before moving.
.SH \fBDELETE OPTIONS\fR
.PP
\fBdelete \<filename\>\fP
.br
.RS
Delete file(s) by filename
.RE
.br
\fB--\fP
.br
.RS
Options end after this point.
.RE
.br
\fB--help, -h\fP
.br
.RS
Prints basic usage of rcb delete.
.RE
.br
\fB--verbose, -v\fP
.br
.RS
Provides verbose information to console.
.RE
.br
\fB--silent, -s\fP
.br
.RS
Silences output to console
.RE
.br
\fB--force, -f\fP
.br
.RS
Forces file deletion
.RE
.br
\fB--no-directorysize\fP
.br
.RS
Don\(aqt save size for filetype of directory.
.RE
.br
.SH AUTHOR
Written by Isfand Mirza.
.SH COPYRIGHT
Copyright © 2024-2025, Isfand Mirza.
