.nh
.TH RCB 1 "0.11.0" RCB "User Manuals"
.SH \fBNAME\fR
rcb-erase
.SH \fBSYNOPSIS\fR
\fBrcb erase\fP [\fIoptions\fP] [\fIarguments\fP]
.br
\fBrcb erase\fP [\fIarguments\fP] [\fIoptions\fP]
.br
\fBrcb erase\fP [\fIoptions\fP]
.br
\fBrcb erase\fP [\fIarguments\fP]
.br
.SH \fBDESCRIPTION\fR
The erase command allows for permanent file removal. This action is not reversible.
.SH \fBERASE OPTIONS\fR
.PP
\fBrcb erase \<id\>
.br
.RS
Erase file(s) by record id.
.RE
.br
\fB--help, -h\fP 
.br
.RS
Prints basic usage of rcb erase.
.RE
.br
\fB--all, -a\fP
.br
.RS
Permanently remove all files.
.RE
.br
\fB--past \<n\>(unit)\fP
.br
.RS
Erase file(s) by relative past time with units: t,s,m,h,d,w,mo,y,c,k,ae.

\fBExample:\fP
.br
\fB$ rcb erase\fP \fI--past 10m\fP

Will erase all files that were deleted 10 minutes ago.

\fBTime Reference Table\fP

| Unit          | shorthand |
.br
| ------------- | --------- |
.br
| Posixtime     | t         |
.br
| Second(s)     | s         |
.br
| Minute(s)     | m         |
.br
| Hour(s)       | h         |
.br
| Day(s)        | d         |
.br
| Week(s)       | w         |
.br
| Month(s)      | mo        |
.br
| Year(s)       | y         |
.br
| Decade(s)     | dec       |
.br
| Century(s)    | c         |
.br
| Millennium(s) | k         |
.br
| Aeon(s)       | ae        |
.br
.RE
.br

\fB--previous\fP
.br
.RS
Erase file(s) by highest execution. Execution is the order in which files were deleted together under the same process.
.RE
.br
\fB--silent, -s\fP
.br
.RS
Silences output to console
.RE
.br
\fB--sql \<s\>\fP
.br
.RS
\fIWARNING UNSAFE:\fP Insert sql statement directly for erase. Must return ID.

\fBExample:\fP
.br
\fB$ rcb erase\fP \fI--sql \(dqSELECT id FROM rcb WHERE file=\[aq]filename\[aq]\(dq\fP
.RE
.SH AUTHOR
Written by Isfand Mirza.
.SH COPYRIGHT
Copyright © 2024-2025, Isfand Mirza.
