'\" t
.\"     Title: rcb-list
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2026-05-13
.\"    Manual: User Manuals
.\"    Source: RCB 0.14.0
.\"  Language: English
.\"
.TH "RCB\-LIST" "1" "2026-05-13" "RCB 0.14.0" "User Manuals"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
rcb-list \- list files in rcb
.SH "SYNOPSIS"
.sp
\fBrcb list\fP [\fIoptions\fP] [\fIarguments\fP]
.br
\fBrcb list\fP [\fIoptions\fP]
.br
\fBrcb list\fP
.br
.SH "DESCRIPTION"
.sp
The list command allows for listing file data inside \fI.rcb/data/rcb.sqlite3\fP
.SH "LIST OPTIONS"
.sp
\fBrcb list\fP
.br
.sp
List everything in record.
.sp
\fB\-\-help\fP, \fB\-h\fP
.br
.sp
Prints basic usage of rcb list.
.sp
\fB\-\-all\fP, \fB\-a\fP
.br
.sp
List everything in record along with total count and total size.
.sp
\fB\-\-past\fP \fI<n>(unit)\fP
.br
.sp
List file(s) by relative past time with units: t,s,m,h,d,w,mo,y,c,k,ae.
.br
\fBExample:\fP
.br
\fB$ rcb list\fP \fI\-\-past 10m\fP
.br
Will list all files that were deleted 10 minutes ago.
.br
\fBTime Reference Table\fP
.TS
allbox tab(:);
ltB ltB.
T{
.sp
Unit
T}:T{
.sp
shorthand
T}
.T&
lt lt.
T{
.sp
Posixtime
T}:T{
.sp
t
T}
T{
.sp
Second(s)
T}:T{
.sp
s
T}
T{
.sp
Minute(s)
T}:T{
.sp
m
T}
T{
.sp
Hour(s)
T}:T{
.sp
h
T}
T{
.sp
Day(s)
T}:T{
.sp
d
T}
T{
.sp
Week(s)
T}:T{
.sp
w
T}
T{
.sp
Month(s)
T}:T{
.sp
mo
T}
T{
.sp
Year(s)
T}:T{
.sp
y
T}
T{
.sp
Decade(s)
T}:T{
.sp
dec
T}
T{
.sp
Century(s)
T}:T{
.sp
c
T}
T{
.sp
Millennium(s)
T}:T{
.sp
k
T}
.TE
.sp
.sp
\fB\-\-previous\fP
.br
.sp
List file(s) by highest execution. Execution is the order in which files were deleted together under the same process.
.sp
\fB\-\-total\-count\fP
.br
.sp
List total count of all files in rcb
.sp
\fB\-\-total\-size\fP
.br
.sp
List total size of all files in rcb
.sp
\fB\-\-human\-readable\fP
.br
.sp
List timestamp as date/time
.sp
\fB\-\-no\-format\fP
.br
.sp
Remove formatting
.sp
\fB\-\-sql\fP \fI<s>\fP
.br
.sp
\fIWARNING UNSAFE:\fP Insert sql statement directly for list.
.br
\fBExample:\fP
.br
\fB$ rcb list\fP \fI\-\-sql "SELECT id FROM rcb WHERE file=\*(Aqfilename\*(Aq"\fP
.SH "AUTHOR"
.sp
Written by Isfand Mirza.
.SH "COPYRIGHT"
.sp
Copyright © 2024–2026, Isfand Mirza.