libs =
import libs += libsqlite3%lib{sqlite3}

#exe{rcb}: {hxx ixx txx cxx}{**} $libs #testscript

info "detected: $cc.target.class"

exe{rcb}: {hxx ixx txx cxx}{** -***/platform/aci/posix/**} $libs: include = ($cc.target.class == 'windows')
exe{rcb}: {hxx ixx txx cxx}{** -***/platform/aci/windows/**} $libs: include = ($cc.target.class != 'windows')

cxx.poptions =+ "-I$out_root" "-I$src_root"